language: php
php:
  - 5.3
  - 5.4
  - 5.5
env:
  - MAGENTO_VERSION="1.8.0.0"
before_script:
  - mkdir magento/
  - git clone git://github.com/EcomDev/MageCI.git ./mageci/
  - ./mageci/bin/mage-ci install magento $MAGENTO_VERSION magento_test -c -t -r http://mage-ci.ecomdev.org
  - composer update
  - CURR_DIR=$(pwd)
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman -O ./mageci/bin/modman
  - chmod +x ./mageci/bin/modman
  - ./mageci/bin/mage-ci install-module magento $CURR_DIR
  - composer install --dev
  - cd magento
script:
  - ../vendor/bin/phpunit --group Sitewards_B2BProfessional
